### ISSUE TITLE
[Isuue] Documentation sidebar scroll jump to top when page change

### ISSUE THREAD

**Issue by iEnzO233** [BayBreezy/ui-thing#52] opened 2024-12-22 06:58 UTC
Hi . first of all thank you for your work its awsome .
the issue is in Documentation when changing page sidebar will jump to top it would be good to stay on current page so when user explore components it wont jump up and scroll down again to see other components

**Comment by BayBreezy** [comment] 2024-12-22 10:44
Hey,

Yeah. I saw this issue and I am not sure how to fix it. I will have to get some help on it.

**Comment by iEnzO233** [comment] 2024-12-24 11:07
you already have router-link-active on that element you can use this on mounted
element.scrollTo({
  top: 100,
  behavior: "smooth",
});

in my mind it should work please let me know it was helpful or not

**Comment by BayBreezy** [comment] 2024-12-24 14:44
I think the issue is with the document driven mode that I am using. 
I may have to migrate to nuxt content v3 or use the catch-all page method instead to fix this issue. I realize that nuxt websites that use the catch-all method don't have this same issue.

**Comment by BayBreezy** [comment] 2024-12-26 15:49
@iEnzO233 I found the problem. It is the `documentDriven` mode.

Not sure when i will be able to update this as it involves changing a lot of how the project is currently structured.

**Comment by BayBreezy** [comment] 2024-12-28 01:52
@iEnzO233 This is now fixed.

Upgrade to content v3 and stuff. Check it out when you have the time. Thanks

**Closed by BayBreezy** 2024-12-28 01:52 UTC
Labels: documentation, help wanted

**Comment by iEnzO233** [comment] 2025-01-01 05:58
@BayBreezy thakns man its great now <3
